ConstantesPadraoUsabilidade =
{
	LIM_SUP_DESENHO = 30,
	LIM_INF_DESENHO = 30,
	LIM_ESQ_DESENHO = 30,
	LIM_DIR_DESENHO = 30,

	DISTANCIA_ENTRE_OBJETOS = 60,
	DISTANCIA_ENTRE_TEXTO_E_CAIXA = 10,
	TAMANHO_FONTE = 18,
	FONTE = 'tiresias',
	TAMANHO_FONTE_TITULO = 18,
	FONTE_TITULO = 'tiresias',
	NEGRITO = 'bold',
	NORMAL = 'plain',

	ESPACO_NIVEL = 20,
	ESPACO_LINHA = 26,

	FONTE_CAMPO_TEXTO = 'tiresias',
	TAMANHO_FONTE_CAMPO_TEXTO = 16
}
